jwt.key.public=classpath:app.pub
jwt.key.private=classpath:app.key
jwt.persistence.password=password
jwt.persistence.salt=626F6F746966756C
jwt.key.id=bootiful
spring.datasource.url=jdbc:postgresql://localhost:5432/mangalsathi_db
spring.datasource.username=mangalsathi_user
spring.datasource.password=mangalsathi_password
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=9000

logging.level.org.springframework.security.authentication=TRACE
logging.level.org.springframework.security.oauth2.server.authorization=TRACE
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG